# Generated by Django 5.2.7 on 2025-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rahaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(upload_to='picture/'),
        ),
    ]
